// Generated by CoffeeScript 1.3.3
(function() {
  var Client;

  Client = (function() {

    function Client() {
      console.log("instanciating new client");
    }

    Client["default"] = function() {
      return console.log("default function of client");
    };

    Client.register = function(name, gender) {
      return console.log("Name " + name + ", gender " + gender);
    };

    return Client;

  })();

  exports.Client = Client;

}).call(this);
