// Generated by CoffeeScript 1.3.3
(function() {
  var User;

  User = {
    "default": function() {
      return console.log("default function of user");
    },
    register: function(name, age) {
      return console.log("Name " + name + ", age " + age);
    }
  };

  exports.User = User;

}).call(this);
